export const premiumProductData: Record<string, { nameEn: string, nameAr: string, descriptionEn: string, descriptionAr: string }[]> = {
    men: [
        { nameEn: "Executive Wool Blazer", nameAr: "بليزر صوف تنفيذي", descriptionEn: "Tailored fit made from Italian wool.", descriptionAr: "قصة مخصصة من الصوف الإيطالي." },
        { nameEn: "Royal Oxford Shirt", nameAr: "قميص أكسفورد الملكي", descriptionEn: "100% long-staple cotton for a crisp look.", descriptionAr: "قطن 100% لمظهر ناصع." },
        { nameEn: "Urban Bomber Jacket", nameAr: "جاكيت بومبر عصري", descriptionEn: "Water-repellent fabric with matte finish.", descriptionAr: "نسيج طارد للماء بلمسة مطفأة." },
        { nameEn: "Merino V-Neck Sweater", nameAr: "كنزة ميرينو بياقة V", descriptionEn: "Lightweight warmth for formal layering.", descriptionAr: "دفء خفيف الوزن للارتداء الرسمي." },
        { nameEn: "Classic Polo Shirt", nameAr: "قميص بولو كلاسيكي", descriptionEn: "Breathable piqué cotton with ribbed cuffs.", descriptionAr: "قطن بيكيه يسمح بالتنفس." },
        { nameEn: "Slim-Fit Chino Pants", nameAr: "بنطال تشينو سليم", descriptionEn: "Versatile stretch cotton for all-day comfort.", descriptionAr: "قطن مطاط مريح طوال اليوم." },
        { nameEn: "Linen Summer Shirt", nameAr: "قميص كتان صيفي", descriptionEn: "Natural linen fabric for cool ventilation.", descriptionAr: "كتان طبيعي لتهوية ممتازة." },
        { nameEn: "Double-Breasted Overcoat", nameAr: "معطف طويل صفين أزرار", descriptionEn: "Heavy wool blend for extreme winter cold.", descriptionAr: "مزيج صوف ثقيل لبرد الشتاء." },
        { nameEn: "Graphic Street Tee", nameAr: "تيشيرت ستريت-وير", descriptionEn: "Oversized fit with modern artistic print.", descriptionAr: "قصة واسعة بطبعة فنية حديثة." },
        { nameEn: "Satin Evening Tuxedo", nameAr: "بدلة توكسيدو ساتان", descriptionEn: "Sharp peak lapels for formal galas.", descriptionAr: "ياقات حادة للمناسبات الرسمية." },
        { nameEn: "Utility Cargo Pants", nameAr: "بنطال كارجو عملي", descriptionEn: "Multiple pockets with reinforced stitching.", descriptionAr: "جيوب متعددة وخياطة معززة." },
        { nameEn: "Techno Windbreaker", nameAr: "سترة واقية من الرياح", descriptionEn: "Lightweight tech fabric for outdoor activities.", descriptionAr: "نسيج تقني خفيف للأنشطة الخارجية." },
        { nameEn: "Knitted Turtleneck", nameAr: "بلوفر بياقة عالية", descriptionEn: "Soft knit texture for a sophisticated look.", descriptionAr: "نسيج ناعم لمظهر متطور." },
        { nameEn: "Denim Trucker Jacket", nameAr: "جاكيت جينز تراكر", descriptionEn: "Iconic rugged design with metal buttons.", descriptionAr: "تصميم قوي بأزرار معدنية." },
        { nameEn: "Performance Gym Hoodie", nameAr: "هودي رياضي للأداء", descriptionEn: "Moisture-wicking fabric for intense workouts.", descriptionAr: "نسيج طارد للعرق للتمارين الشاقة." }
    ],
    women: [
        { nameEn: "Silk Gala Gown", nameAr: "فستان الحفلات الحريري", descriptionEn: "Flowing mulberry silk for ultimate elegance.", descriptionAr: "حرير التوت لجمالية مطلقة." },
        { nameEn: "Empress Velvet Blazer", nameAr: "بليزر مخمل الإمبراطورة", descriptionEn: "Structured shoulders and rich texture.", descriptionAr: "أكتاف محددة وقوام غني." },
        { nameEn: "Cashmere Cloud Cardigan", nameAr: "كارديجان كشمير السحاب", descriptionEn: "Pure Mongolian cashmere for softness.", descriptionAr: "كشمير منغولي خالص للنعومة." },
        { nameEn: "Boho Chiffon Maxi", nameAr: "فستان ماكسي بوهيمي", descriptionEn: "Lightweight with floral patterns.", descriptionAr: "خفيف الوزن بنقوش زهور." },
        { nameEn: "Tailored Pencil Skirt", nameAr: "تنورة بنسل محددة", descriptionEn: "High-waist fit for a professional silhouette.", descriptionAr: "خصر عالٍ لمظهر مهني." },
        { nameEn: "Lace Evening Blouse", nameAr: "بلوزة دانتيل للسهرات", descriptionEn: "Intricate lace detailing with silk lining.", descriptionAr: "تفاصيل دانتيل مع بطانة حرير." },
        { nameEn: "Leather Moto Jacket", nameAr: "جاكيت جلد راكبي الدراجات", descriptionEn: "Genuine leather with silver zip accents.", descriptionAr: "جلد طبيعي بلمسات فضية." },
        { nameEn: "A-Line Summer Dress", nameAr: "فستان صيفي واسع", descriptionEn: "Breathable cotton with a flared hem.", descriptionAr: "قطن مريح بقصة واسعة." },
        { nameEn: "Embroidered Kaftan", nameAr: "قفطان مطرز", descriptionEn: "Traditional motifs with a modern cut.", descriptionAr: "زخارف تقليدية بقصة حديثة." },
        { nameEn: "Satin Slip Dress", nameAr: "فستان ساتان ناعم", descriptionEn: "Minimalist design for effortless elegance.", descriptionAr: "تصميم بسيط لأناقة سهلة." },
        { nameEn: "Pleated Midi Skirt", nameAr: "تنورة ميدي مكسرة", descriptionEn: "Flowy satin pleats for a dynamic look.", descriptionAr: "كسرات ساتان لمظهر حيوي." },
        { nameEn: "Work-Wear Trench Coat", nameAr: "معطف ترنش للعمل", descriptionEn: "Classic belted design for rainy days.", descriptionAr: "تصميم كلاسيكي بحزام للمطر." },
        { nameEn: "Off-Shoulder Party Top", nameAr: "بلوزة مكشوفة الأكتاف", descriptionEn: "Trendy cut for social gatherings.", descriptionAr: "قصة عصرية للتجمعات." },
        { nameEn: "Cozy Oversized Knit", nameAr: "كنزة صوف واسعة", descriptionEn: "Chunky knit for maximum winter comfort.", descriptionAr: "صوف سميك لراحة شتوية." },
        { nameEn: "Denim Overall Dress", nameAr: "فستان جينز (سليب)", descriptionEn: "Casual denim for a youthful vibe.", descriptionAr: "جينز كاجوال لمظهر شبابي." }
    ],
    kids: [
        { nameEn: "Little Hero Denim Jacket", nameAr: "جاكيت جينز البطل", descriptionEn: "Rugged denim with fleece lining.", descriptionAr: "جينز قوي ببطانة صوف." },
        { nameEn: "Sparkle Tulle Dress", nameAr: "فستان تول لامع", descriptionEn: "Layers of tulle for celebrations.", descriptionAr: "طبقات من التول للاحتفالات." },
        { nameEn: "Dino Cotton Pajamas", nameAr: "بيجاما ديناصور قطنية", descriptionEn: "Soft organic cotton with fun prints.", descriptionAr: "قطن عضوي بطبعات مرحة." },
        { nameEn: "Active Explorer Tracksuit", nameAr: "ترينج المستكشف النشط", descriptionEn: "Flexible fabric for playtime.", descriptionAr: "نسيج مرن وقت اللعب." },
        { nameEn: "Junior Polo Shirt", nameAr: "قميص بولو للصغار", descriptionEn: "Classic style for school and events.", descriptionAr: "ستايل كلاسيكي للمدرسة." },
        { nameEn: "Rainy Day Yellow Coat", nameAr: "معطف المطر الأصفر", descriptionEn: "Waterproof with a cozy hood.", descriptionAr: "مقاوم للماء مع غطاء رأس." },
        { nameEn: "Superhero Graphic Tee", nameAr: "تيشيرت بطل خارق", descriptionEn: "Cotton jersey with vibrant prints.", descriptionAr: "قطن جيرسي بطبعات زاهية." },
        { nameEn: "Fleece Winter Onesie", nameAr: "سلوبيت صوف شتوي", descriptionEn: "Full-body warmth for infants.", descriptionAr: "دفء كامل للجسم للرضع." },
        { nameEn: "Skater Twill Chinos", nameAr: "بنطال تشينو تويل", descriptionEn: "Durable fabric for active kids.", descriptionAr: "نسيج متين للأطفال النشطين." },
        { nameEn: "Butterfly Garden Skirt", nameAr: "تنورة حديقة الفراشات", descriptionEn: "Colorful prints with elastic waist.", descriptionAr: "طبعات ملونة بخصر مطاطي." },
        { nameEn: "Cozy Sherpa Hoodie", nameAr: "هودي شيربا دافئ", descriptionEn: "Fluffy lining for extra insulation.", descriptionAr: "بطانة ناعمة لعزل إضافي." },
        { nameEn: "Striped Sailor Set", nameAr: "طقم البحار المخطط", descriptionEn: "Nautical style for summer outings.", descriptionAr: "ستايل بحري للخروجات." },
        { nameEn: "Rugged Combat Shorts", nameAr: "شورت كارجو قوي", descriptionEn: "Tough cotton for outdoor adventures.", descriptionAr: "قطن قوي للمغامرات." },
        { nameEn: "Princess Velvet Cape", nameAr: "كيب مخمل الأميرة", descriptionEn: "Elegant layering for formal events.", descriptionAr: "طبقة أنيقة للمناسبات." },
        { nameEn: "Puffy Winter Vest", nameAr: "فيست شتوي منفوخ", descriptionEn: "Quilted design to keep the core warm.", descriptionAr: "تصميم مبطن لتدفئة الجسم." }
    ],
    shoes: [
        { nameEn: "Royal Italian Oxford", nameAr: "حذاء أكسفورد إيطالي", descriptionEn: "Hand-burnished calfskin leather.", descriptionAr: "جلد عجل ملمع يدوياً." },
        { nameEn: "Velvet Night Stilettos", nameAr: "حذاء ستيلتو مخملي", descriptionEn: "High-fashion heels for comfort.", descriptionAr: "كعب عالٍ أنيق ومريح." },
        { nameEn: "Cloud-Walk Sneakers", nameAr: "حذاء ركض السحاب", descriptionEn: "Responsive foam technology.", descriptionAr: "تقنية رغوة مستجيبة." },
        { nameEn: "Heritage Chelsea Boots", nameAr: "بوت تشيلسي تراثي", descriptionEn: "Classic suede with elastic panels.", descriptionAr: "جلد سويدي بقطع مطاطية." },
        { nameEn: "Gilded Evening Sandals", nameAr: "صندل سهرة مذهب", descriptionEn: "Gold-toned with crystal accents.", descriptionAr: "درجات ذهبية مع كريستال." },
        { nameEn: "Waterproof Hikers", nameAr: "حذاء مغامرات مقاوم للماء", descriptionEn: "Superior ankle support for trails.", descriptionAr: "دعم فائق للكاحل للمسارات." },
        { nameEn: "Minimalist Loafers", nameAr: "حذاء لوفر بسيط", descriptionEn: "Soft grain leather for business.", descriptionAr: "جلد ناعم للعمل." },
        { nameEn: "Neon Pulse Trainers", nameAr: "حذاء نيون عصري", descriptionEn: "Bold colors and chunky soles.", descriptionAr: "ألوان جريئة ونعل سميك." },
        { nameEn: "Monk Strap Elite", nameAr: "حذاء مونك ستراب", descriptionEn: "Double buckle polished leather.", descriptionAr: "إبزيم مزدوج وجلد مصقول." },
        { nameEn: "Crystal Satin Pumps", nameAr: "حذاء ساتان بالكريستال", descriptionEn: "Handcrafted bow on the toe.", descriptionAr: "فيونكة مصنوعة يدوياً." },
        { nameEn: "Arctic Fur Boots", nameAr: "بوت شتوي بالفرو", descriptionEn: "Insulated for sub-zero temps.", descriptionAr: "معزول لدرجات الحرارة المنخفضة." },
        { nameEn: "Canvas Espadrilles", nameAr: "حذاء إسبادريل كانفاس", descriptionEn: "Breathable jute sole for summer.", descriptionAr: "نعل جوت للصيف." },
        { nameEn: "Combat Rebel Boots", nameAr: "بوت قتالي متمرد", descriptionEn: "Heavy-duty with side-zip.", descriptionAr: "شديد التحمل بسحاب جانبي." },
        { nameEn: "Gold-Thread Slippers", nameAr: "حذاء منزلي مذهب", descriptionEn: "Velvet with genuine gold thread.", descriptionAr: "مخمل بخيوط ذهبية أصيلة." },
        { nameEn: "Aero-Lite Walking Flats", nameAr: "حذاء مسطح خفيف", descriptionEn: "Orthopedic support for mobility.", descriptionAr: "دعم طبي للحركة." }
    ],
    jeans: [
        { nameEn: "Signature Slim Indigo", nameAr: "جينز سليم إنديجو", descriptionEn: "Premium denim with stretch.", descriptionAr: "دنيم فاخر مع مرونة." },
        { nameEn: "Obsidian Black Skinny", nameAr: "جينز أسود سكيني", descriptionEn: "Color-stay technology.", descriptionAr: "تقنية تثبيت اللون." },
        { nameEn: "Vintage Straight Leg", nameAr: "جينز مستقيم تراثي", descriptionEn: "90s inspired rigid cotton.", descriptionAr: "مستوحى من التسعينيات." },
        { nameEn: "Sky Blue Tapered", nameAr: "جينز أزرق سماوي", descriptionEn: "High-waist feminine silhouette.", descriptionAr: "خصر عالٍ لمظهر أنثوي." },
        { nameEn: "Distressed Streetwear", nameAr: "جينز ممزق عصري", descriptionEn: "Hand-abraded details.", descriptionAr: "تفاصيل ممزقة يدوياً." },
        { nameEn: "Midnight Raw Selvage", nameAr: "جينز سيلفدج خام", descriptionEn: "Develops unique wear patterns.", descriptionAr: "يكتسب أنماط ارتداء فريدة." },
        { nameEn: "Grey Work Jeans", nameAr: "جينز رمادي للعمل", descriptionEn: "Polished office-ready wash.", descriptionAr: "غسيل مناسب للمكتب." },
        { nameEn: "Athletic Performance", nameAr: "جينز أداء رياضي", descriptionEn: "Extra room for active days.", descriptionAr: "مساحة إضافية للحركة." },
        { nameEn: "Retro Flare Bell-Bottoms", nameAr: "جينز واسع كلاسيكي", descriptionEn: "Dramatic 70s inspired cut.", descriptionAr: "قصة مستوحاة من السبعينيات." },
        { nameEn: "Cargo Utility Denim", nameAr: "جينز كارجو وظيفي", descriptionEn: "Side pockets and reinforced.", descriptionAr: "جيوب جانبية وخياطة معززة." },
        { nameEn: "Acid Wash Rocker", nameAr: "جينز أسيد-واش", descriptionEn: "Bold 80s wash with metal trim.", descriptionAr: "غسيل جريء بلمسات معدنية." },
        { nameEn: "Cloud-Soft Relaxed", nameAr: "جينز مريح ناعم", descriptionEn: "Cotton-lyocell breathable blend.", descriptionAr: "مزيج قطن وليوسيل مريح." },
        { nameEn: "Shadow Grey Bootcut", nameAr: "جينز بوت-كت رمادي", descriptionEn: "Subtle flare at the ankle.", descriptionAr: "اتساع طفيف عند الكاحل." },
        { nameEn: "Artisan Patchwork", nameAr: "جينز مرقع حرفي", descriptionEn: "Multi-toned avant-garde patches.", descriptionAr: "قطع دنيم متعددة الدرجات." },
        { nameEn: "Winter-Lined Summit", nameAr: "جينز مبطن حراري", descriptionEn: "Hidden fleece for extreme cold.", descriptionAr: "بطانة صوف للبرد القارس." }
    ],
    lingerie: [
        { nameEn: "Silk Majesty Set", nameAr: "طقم جلالة الحرير", descriptionEn: "French lace and 100% silk.", descriptionAr: "دانتيل فرنسي وحرير 100%." },
        { nameEn: "Midnight Satin Robe", nameAr: "روب ساتان طويل", descriptionEn: "Floor-length elegant drape.", descriptionAr: "انسدال أنيق يصل للأرض." },
        { nameEn: "Invisible Comfort", nameAr: "لانجري غير مرئي", descriptionEn: "Seamless edges for daily wear.", descriptionAr: "حواف بدون خياطة لليومي." },
        { nameEn: "Emerald Velvet Bodysuit", nameAr: "بودي-سوت مخملي", descriptionEn: "Stretch velvet with lace inserts.", descriptionAr: "مخمل مطاطي مع دانتيل." },
        { nameEn: "Cotton Bralette", nameAr: "براليت قطن السحاب", descriptionEn: "Organic cotton, no underwire.", descriptionAr: "قطن عضوي بدون أسلاك." },
        { nameEn: "Floral Corset", nameAr: "كورسيه مطرز بالزهور", descriptionEn: "Structured fit with ribbon ties.", descriptionAr: "قصة محددة بأربطة ستان." },
        { nameEn: "Sheer Baby-doll", nameAr: "بيبي-دول شفاف", descriptionEn: "Lightweight chiffon and ruffles.", descriptionAr: "شيفون خفيف مع كشكشة." },
        { nameEn: "Bridal Ivory Gown", nameAr: "ثوب نوم العروس العاجي", descriptionEn: "Intricate white-on-white lace.", descriptionAr: "دانتيل أبيض معقد للعروس." },
        { nameEn: "Onyx Mesh Teddy", nameAr: "تيدي شبكي أسود", descriptionEn: "Modern architectural design.", descriptionAr: "تصميم معماري حديث." },
        { nameEn: "Rose Quartz Slip", nameAr: "قميص نوم وردي", descriptionEn: "Simple fluid bias cut.", descriptionAr: "قصة مائلة انسيابية." },
        { nameEn: "Lace Kimono Luxury", nameAr: "كيمونو دانتيل فاخر", descriptionEn: "Bohemian sleeves, full lace.", descriptionAr: "أكمام واسعة ودانتيل كامل." },
        { nameEn: "Modal Sleep Set", nameAr: "طقم نوم مريح", descriptionEn: "Stays cool all night long.", descriptionAr: "يحافظ على البرودة طوال الليل." },
        { nameEn: "Gold Guipure Set", nameAr: "طقم جيبير مذهب", descriptionEn: "Metallic highlights for evening.", descriptionAr: "لمسات معدنية للسهرة." },
        { nameEn: "Active Sport Bra", nameAr: "حمالة رياضية", descriptionEn: "High-impact moisture-wicking.", descriptionAr: "دعم عالي وطارد للرطوبة." },
        { nameEn: "Vintage Polka Romper", nameAr: "رومبر منقط عتيق", descriptionEn: "Soft rayon retro design.", descriptionAr: "تصميم ريترو من الريون." }
    ],
    accessories: [
        { nameEn: "Leather Briefcase", nameAr: "حقيبة عمل جلدية", descriptionEn: "Italian leather with tech slots.", descriptionAr: "جلد إيطالي مع أقسام تقنية." },
        { nameEn: "Chronograph Watch", nameAr: "ساعة كرونوغراف", descriptionEn: "Swiss movement, sapphire glass.", descriptionAr: "حركة سويسرية وزجاج ياقوت." },
        { nameEn: "Aviator Shades", nameAr: "نظارات طيار", descriptionEn: "Polarized UV protection.", descriptionAr: "نظارات مستقطبة بحماية UV." },
        { nameEn: "Braided Leather Belt", nameAr: "حزام جلدي مضفر", descriptionEn: "Hand-woven genuine leather.", descriptionAr: "جلد طبيعي منسوج يدوياً." },
        { nameEn: "Cashmere Scarf", nameAr: "وشاح كشمير تراثي", descriptionEn: "Pashmina-grade softness.", descriptionAr: "نعومة بجودة الباشمينا." },
        { nameEn: "Diamond Cufflinks", nameAr: "أزرار أكمام ألماس", descriptionEn: "Sterling silver with lab diamond.", descriptionAr: "فضة مع ألماس مختبري." },
        { nameEn: "Canvas Backpack", nameAr: "حقيبة ظهر كانفاس", descriptionEn: "Water-resistant tech storage.", descriptionAr: "مقاومة للماء وتخزن التقنية." },
        { nameEn: "Evening Clutch", nameAr: "حقيبة سهرة مذهبة", descriptionEn: "Detachable chain, silk lining.", descriptionAr: "سلسلة قابلة للفصل وبطانة حرير." },
        { nameEn: "Silk Pocket Square", nameAr: "منديل جيب حريري", descriptionEn: "Hand-rolled artistic print.", descriptionAr: "طبعة فنية وحواف ملفوفة." },
        { nameEn: "Tech Leather Gloves", nameAr: "قفازات جلد للمس", descriptionEn: "Sheepskin, smartphone compatible.", descriptionAr: "جلد غنم متوافق مع الشاشات." },
        { nameEn: "Enamel Earrings", nameAr: "أقراط مينا هندسية", descriptionEn: "Minimalist gold plating.", descriptionAr: "طلاء ذهبي وتصميم بسيط." },
        { nameEn: "Felt Fedora Hat", nameAr: "قبعة فيدورا كلاسيكية", descriptionEn: "Structured wool with ribbon.", descriptionAr: "لباد صوفي محدد بشريط." },
        { nameEn: "Silver ID Bracelet", nameAr: "سوار فضة إسترليني", descriptionEn: "Heavy-link chain for engraving.", descriptionAr: "سلسلة ثقيلة قابلة للحفر." },
        { nameEn: "Travel Passport Wallet", nameAr: "محفظة سفر فاخرة", descriptionEn: "RFID-blocking leather slots.", descriptionAr: "جلد يحجب الترددات اللاسلكية." },
        { nameEn: "Velvet Bow Clip", nameAr: "مشبك شعر مخملي", descriptionEn: "Romantic oversized bow design.", descriptionAr: "فيونكة رومانسية كبيرة الحجم." }
    ]
};