import { mutation } from "./_generated/server";
import { v } from "convex/values";

const colors = {
    black: { name: 'Black', nameAr: 'أسود', hex: '#000000' },
    white: { name: 'White', nameAr: 'أبيض', hex: '#FFFFFF' },
    navy: { name: 'Navy', nameAr: 'كحلي', hex: '#1a237e' },
    red: { name: 'Red', nameAr: 'أحمر', hex: '#c62828' },
    blue: { name: 'Blue', nameAr: 'أزرق', hex: '#1976d2' },
    green: { name: 'Green', nameAr: 'أخضر', hex: '#388e3c' },
    gray: { name: 'Gray', nameAr: 'رمادي', hex: '#616161' },
    beige: { name: 'Beige', nameAr: 'بيج', hex: '#d7ccc8' },
    brown: { name: 'Brown', nameAr: 'بني', hex: '#5d4037' },
    pink: { name: 'Pink', nameAr: 'وردي', hex: '#e91e63' },
    purple: { name: 'Purple', nameAr: 'بنفسجي', hex: '#7b1fa2' },
    yellow: { name: 'Yellow', nameAr: 'أصفر', hex: '#fbc02d' },
    olive: { name: 'Olive', nameAr: 'زيتوني', hex: '#556b2f' },
    silver: { name: 'Silver', nameAr: 'فضي', hex: '#c0c0c0' },
};

export const run = mutation({
  args: {},
  handler: async (ctx) => {
    const productData = [
        {
            id: 'men-1',
            name: 'Classic Slim Fit Shirt',
            nameAr: 'قميص كلاسيكي ضيق',
            description: 'A timeless slim fit cotton shirt perfect for any occasion. Features a spread collar and single button cuffs.',
            descriptionAr: 'قميص قطني كلاسيكي ضيق مثالي لأي مناسبة. يتميز بياقة منتشرة وأكمام بزر واحد.',
            price: 49.99,
            originalPrice: 69.99,
            images: [
                'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800',
                'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800',
            ],
            category: 'men',
            sizes: ['S', 'M', 'L', 'XL', 'XXL'],
            colors: [colors.white, colors.navy, colors.black],
            inStock: true,
            stock: 45,
            featured: true,
            newArrival: true,
            rating: 4.8,
            reviews: 124,
        },
        {
            id: 'men-2',
            name: 'Premium Polo Shirt',
            nameAr: 'بولو فاخر',
            description: 'Breathable cotton polo shirt with ribbed collar. Perfect for casual and semi-formal occasions.',
            descriptionAr: 'قميص بولو قطني متنفس بياقة مضلعة. مثالي للمناسبات العادية وشبه الرسمية.',
            price: 39.99,
            images: [
                'https://images.unsplash.com/photo-1625910513413-5fc5e0389748?w=800',
            ],
            category: 'men',
            sizes: ['S', 'M', 'L', 'XL'],
            colors: [colors.navy, colors.white, colors.green, colors.red],
            inStock: true,
            stock: 30,
            featured: false,
            newArrival: false,
            rating: 4.5,
            reviews: 89,
        },
        {
            id: 'men-3',
            name: 'Casual Blazer',
            nameAr: 'بليزر كاجوال',
            description: 'Modern slim-fit blazer crafted from premium wool blend. Features notch lapels and two-button closure.',
            descriptionAr: 'بليزر عصري ضيق مصنوع من مزيج صوف فاخر. يتميز بطية صدر وإغلاق بزرين.',
            price: 149.99,
            originalPrice: 199.99,
            images: [
                'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800',
            ],
            category: 'men',
            sizes: ['S', 'M', 'L', 'XL'],
            colors: [colors.navy, colors.black, colors.gray],
            inStock: true,
            stock: 20,
            featured: true,
            newArrival: false,
            rating: 4.9,
            reviews: 56,
        },
        {
            id: 'men-4',
            name: 'Cotton Crew Neck T-Shirt',
            nameAr: 'تي شيرت قطني برقبة دائرية',
            description: '100% organic cotton t-shirt with a comfortable relaxed fit. Ideal for everyday wear.',
            descriptionAr: 'تي شيرت قطني عضوي 100% بقصة مريحة. مثالي للارتداء اليومي.',
            price: 24.99,
            images: [
                'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800',
            ],
            category: 'men',
            sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
            colors: [colors.white, colors.black, colors.gray, colors.navy],
            inStock: true,
            stock: 100,
            featured: false,
            newArrival: true,
            rating: 4.6,
            reviews: 203,
        },
        {
            id: 'men-5',
            name: 'Wool Overcoat',
            nameAr: 'معطف صوفي',
            description: 'Luxurious wool overcoat with a timeless design. Features a notched lapel and hidden button closure.',
            descriptionAr: 'معطف صوفي فاخر بتصميم خالد. يتميز بطية صدر وإغلاق بأزرار مخفية.',
            price: 299.99,
            originalPrice: 399.99,
            images: [
                'https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=800',
            ],
            category: 'men',
            sizes: ['S', 'M', 'L', 'XL'],
            colors: [colors.black, colors.navy, colors.gray],
            inStock: true,
            stock: 15,
            featured: true,
            newArrival: false,
            rating: 4.9,
            reviews: 42,
        },
        {
            id: 'men-6',
            name: 'Urban Leather Jacket',
            nameAr: 'جاكيت جلدي عصري',
            description: 'Premium faux leather jacket with metallic zippers and a sleek urban look.',
            descriptionAr: 'جاكيت جلد صناعي فاخر بسحابات معدنية ومظهر عصري أنيق.',
            price: 189.99,
            images: [
                'https://res.cloudinary.com/dfq1xxerr/image/upload/v1/products/men-leather-jacket',
            ],
            category: 'men',
            sizes: ['M', 'L', 'XL'],
            colors: [colors.black, colors.brown],
            inStock: true,
            stock: 12,
            newArrival: true,
            rating: 4.7,
            reviews: 35,
        },
        {
            id: 'women-1',
            name: 'Elegant Maxi Dress',
            nameAr: 'فستان ماكسي أنيق',
            description: 'Flowing maxi dress with a flattering silhouette. Perfect for summer evenings and special occasions.',
            descriptionAr: 'فستان ماكسي انسيابي بقصة مميزة. مثالي لأمسيات الصيف والمناسبات الخاصة.',
            price: 89.99,
            originalPrice: 119.99,
            images: [
                'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800',
            ],
            category: 'women',
            sizes: ['XS', 'S', 'M', 'L', 'XL'],
            colors: [colors.black, colors.red, colors.navy],
            inStock: true,
            stock: 35,
            featured: true,
            newArrival: true,
            rating: 4.8,
            reviews: 156,
        },
        {
            id: 'women-2',
            name: ' Silk Blouse',
            nameAr: 'بلوزة حريرية',
            description: 'Luxurious silk blouse with delicate details. A versatile piece for work or weekend.',
            descriptionAr: 'بلوزة حريرية فاخرة بتفاصيل دقيقة. قطعة متعددة الاستخدامات للعمل أو عطلة نهاية الأسبوع.',
            price: 79.99,
            images: [
                'https://images.unsplash.com/photo-1564257631407-4deb1f99d992?w=800',
            ],
            category: 'women',
            sizes: ['XS', 'S', 'M', 'L'],
            colors: [colors.white, colors.pink, colors.beige],
            inStock: true,
            stock: 25,
            featured: false,
            newArrival: true,
            rating: 4.7,
            reviews: 89,
        },
        {
            id: 'women-3',
            name: 'Tailored Blazer',
            nameAr: 'بليزر مفصل',
            description: 'Sophisticated tailored blazer with a modern cut. Perfect for the office or smart-casual occasions.',
            descriptionAr: 'بليزر مفصل راقي بقصة عصرية. مثالي للمكتب أو المناسبات شبه الرسمية.',
            price: 129.99,
            images: [
                'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800',
            ],
            category: 'women',
            sizes: ['XS', 'S', 'M', 'L', 'XL'],
            colors: [colors.black, colors.beige, colors.navy],
            inStock: true,
            stock: 18,
            featured: true,
            newArrival: false,
            rating: 4.9,
            reviews: 67,
        },
        {
            id: 'women-4',
            name: 'Cashmere Sweater',
            nameAr: 'سترة كشمير',
            description: 'Ultra-soft cashmere sweater for ultimate comfort. Features a relaxed fit and ribbed trim.',
            descriptionAr: 'سترة كشمير فائقة النعومة للراحة القصوى. تتميز بقصة مريحة وحواف مضلعة.',
            price: 159.99,
            originalPrice: 199.99,
            images: [
                'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800',
            ],
            category: 'women',
            sizes: ['XS', 'S', 'M', 'L'],
            colors: [colors.beige, colors.gray, colors.pink],
            inStock: true,
            stock: 10,
            featured: false,
            newArrival: false,
            rating: 4.8,
            reviews: 112,
        },
        {
            id: 'women-5',
            name: 'Pleated Midi Skirt',
            nameAr: 'تنورة ميدي مطوية',
            description: 'Elegant pleated midi skirt with a flowing silhouette. Pairs beautifully with any top.',
            descriptionAr: 'تنورة ميدي مطوية أنيقة بقصة انسيابية. تتناسق بشكل جميل مع أي قطعة علوية.',
            price: 69.99,
            images: [
                'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=800',
            ],
            category: 'women',
            sizes: ['XS', 'S', 'M', 'L', 'XL'],
            colors: [colors.black, colors.navy, colors.beige],
            inStock: true,
            stock: 40,
            featured: true,
            newArrival: true,
            rating: 4.6,
            reviews: 78,
        },
        {
            id: 'women-6',
            name: 'Floral Summer Jumpsuit',
            nameAr: 'جمبسوت صيفي مشجر',
            description: 'Lightweight floral jumpsuit with a waist tie. Effortlessly stylish for sunny days.',
            descriptionAr: 'جمبسوت مشجر خفيف برباط خصر. أنيق وبسيط للأيام المشمسة.',
            price: 74.99,
            images: [
                'https://res.cloudinary.com/dfq1xxerr/image/upload/v1/products/women-jumpsuit',
            ],
            category: 'women',
            sizes: ['S', 'M', 'L'],
            colors: [colors.yellow, colors.pink, colors.blue],
            inStock: true,
            stock: 22,
            newArrival: true,
            rating: 4.5,
            reviews: 48,
        },
        {
            id: 'kids-1',
            name: 'Colorful Graphic T-Shirt',
            nameAr: 'تي شيرت ملون مطبوع',
            description: 'Fun and vibrant graphic t-shirt for kids. Made from soft, durable cotton.',
            descriptionAr: 'تي شيرت مطبوع ممتع وملون للأطفال. مصنوع من قطن ناعم ومتين.',
            price: 19.99,
            images: [
                'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=800',
            ],
            category: 'kids',
            sizes: ['2-3Y', '4-5Y', '6-7Y', '8-9Y', '10-11Y'],
            colors: [colors.blue, colors.red, colors.yellow],
            inStock: true,
            stock: 60,
            featured: false,
            newArrival: true,
            rating: 4.7,
            reviews: 145,
        },
        {
            id: 'kids-2',
            name: 'Denim Dungarees',
            nameAr: 'سالوبيت جينز',
            description: 'Classic denim dungarees with adjustable straps. Comfortable and stylish for everyday play.',
            descriptionAr: 'سالوبيت جينز كلاسيكي بأحزمة قابلة للتعديل. مريح وأنيق للعب اليومي.',
            price: 34.99,
            images: [
                'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800',
            ],
            category: 'kids',
            sizes: ['2-3Y', '4-5Y', '6-7Y', '8-9Y'],
            colors: [colors.blue, colors.black],
            inStock: true,
            stock: 28,
            featured: true,
            newArrival: false,
            rating: 4.8,
            reviews: 92,
        },
        {
            id: 'kids-3',
            name: 'Cozy Hoodie',
            nameAr: 'هودي مريح',
            description: 'Super soft fleece hoodie to keep kids warm. Features a front kangaroo pocket.',
            descriptionAr: 'هودي صوف فائق النعومة للحفاظ على دفء الأطفال. يتميز بجيب كنغر أمامي.',
            price: 29.99,
            originalPrice: 39.99,
            images: [
                'https://images.unsplash.com/photo-1445796886651-d31a2c15f3ce?w=800',
            ],
            category: 'kids',
            sizes: ['2-3Y', '4-5Y', '6-7Y', '8-9Y', '10-11Y'],
            colors: [colors.gray, colors.navy, colors.pink],
            inStock: true,
            stock: 50,
            featured: false,
            newArrival: true,
            rating: 4.9,
            reviews: 178,
        },
        {
            id: 'kids-4',
            name: 'Party Dress',
            nameAr: 'فستان حفلات',
            description: 'Beautiful tulle party dress perfect for special occasions. Features sparkly details.',
            descriptionAr: 'فستان حفلات تول جميل مثالي للمناسبات الخاصة. يتميز بتفاصيل لامعة.',
            price: 49.99,
            images: [
                'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=800',
            ],
            category: 'kids',
            sizes: ['2-3Y', '4-5Y', '6-7Y', '8-9Y'],
            colors: [colors.pink, colors.white, colors.purple],
            inStock: true,
            stock: 14,
            featured: true,
            newArrival: false,
            rating: 4.8,
            reviews: 64,
        },
        {
            id: 'kids-5',
            name: 'Playtime Sneakers',
            nameAr: 'حذاء رياضي للعب',
            description: 'Durable and comfortable sneakers designed for active kids. Easy velcro straps.',
            descriptionAr: 'حذاء رياضي متين ومريح مصمم للأطفال النشطين. أحزمة فيلكرو سهلة.',
            price: 44.99,
            images: [
                'https://res.cloudinary.com/dfq1xxerr/image/upload/v1/products/kids-sneakers',
            ],
            category: 'kids',
            sizes: ['25', '26', '27', '28', '29', '30'],
            colors: [colors.blue, colors.pink, colors.white],
            inStock: true,
            stock: 45,
            newArrival: true,
            rating: 4.6,
            reviews: 38,
        },
        {
            id: 'shoes-1',
            name: 'Classic Leather Sneakers',
            nameAr: 'أحذية رياضية جلدية كلاسيكية',
            description: 'Premium leather sneakers with cushioned insole. A timeless design for everyday wear.',
            descriptionAr: 'أحذية رياضية جلدية فاخرة بنعل داخلي مبطن. تصميم خالد للارتداء اليومي.',
            price: 119.99,
            originalPrice: 149.99,
            images: [
                'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800',
            ],
            category: 'shoes',
            sizes: ['38', '39', '40', '41', '42', '43', '44', '45'],
            colors: [colors.white, colors.black],
            inStock: true,
            stock: 25,
            featured: true,
            newArrival: true,
            rating: 4.9,
            reviews: 234,
        },
        {
            id: 'shoes-2',
            name: 'Running Shoes Pro',
            nameAr: 'حذاء جري احترافي',
            description: 'High-performance running shoes with advanced cushioning technology.',
            descriptionAr: 'حذاء جري عالي الأداء بتقنية توسيد متقدمة.',
            price: 159.99,
            images: [
                'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800',
            ],
            category: 'shoes',
            sizes: ['38', '39', '40', '41', '42', '43', '44'],
            colors: [colors.red, colors.black, colors.blue],
            inStock: true,
            stock: 30,
            featured: false,
            newArrival: true,
            rating: 4.7,
            reviews: 189,
        },
        {
            id: 'shoes-3',
            name: 'Elegant Heels',
            nameAr: 'كعب أنيق',
            description: 'Sophisticated stiletto heels for special occasions. Features a comfortable padded footbed.',
            descriptionAr: 'كعب عالي راقي للمناسبات الخاصة. يتميز بنعل داخلي مبطن مريح.',
            price: 99.99,
            images: [
                'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800',
            ],
            category: 'shoes',
            sizes: ['36', '37', '38', '39', '40', '41'],
            colors: [colors.black, colors.red, colors.beige],
            inStock: true,
            stock: 12,
            featured: true,
            newArrival: false,
            rating: 4.6,
            reviews: 156,
        },
        {
            id: 'shoes-4',
            name: 'Chelsea Boots',
            nameAr: 'بوت تشيلسي',
            description: 'Classic Chelsea boots in premium leather. Features elastic side panels for easy on/off.',
            descriptionAr: 'بوت تشيلسي كلاسيكي من الجلد الفاخر. يتميز بألواح جانبية مرنة لسهولة الارتداء.',
            price: 179.99,
            originalPrice: 219.99,
            images: [
                'https://images.unsplash.com/photo-1638953952787-6f87b4e64a77?w=800',
            ],
            category: 'shoes',
            sizes: ['39', '40', '41', '42', '43', '44', '45'],
            colors: [colors.black, colors.brown],
            inStock: true,
            stock: 8,
            featured: false,
            newArrival: false,
            rating: 4.8,
            reviews: 123,
        },
        {
            id: 'shoes-5',
            name: 'Suede Minimalist Loafers',
            nameAr: 'لوفر شمواه بسيط',
            description: 'Soft suede loafers with a minimalist aesthetic. Perfect for both casual and formal settings.',
            descriptionAr: 'لوفر من الشمواه الناعم بلمسة جمالية بسيطة. مثالية للمناسبات الرسمية وغير الرسمية.',
            price: 139.99,
            images: [
                'https://res.cloudinary.com/dfq1xxerr/image/upload/v1/products/shoes-loafers',
            ],
            category: 'shoes',
            sizes: ['40', '41', '42', '43', '44'],
            colors: [colors.beige, colors.navy, colors.brown],
            inStock: true,
            stock: 15,
            newArrival: true,
            rating: 4.8,
            reviews: 24,
        },
        {
            id: 'lingerie-1',
            name: 'Lace Bralette Set',
            nameAr: 'طقم براليت دانتيل',
            description: 'Delicate lace bralette with matching briefs. Comfortable yet elegant.',
            descriptionAr: 'براليت دانتيل رقيق مع سروال مطابق. مريح وأنيق.',
            price: 49.99,
            images: [
                'https://images.unsplash.com/photo-1617331721458-bd3bd3f9c7f8?w=800',
            ],
            category: 'lingerie',
            sizes: ['XS', 'S', 'M', 'L'],
            colors: [colors.black, colors.white, colors.pink],
            inStock: true,
            stock: 45,
            featured: true,
            newArrival: true,
            rating: 4.7,
            reviews: 98,
        },
        {
            id: 'lingerie-2',
            name: 'Silk Pajama Set',
            nameAr: 'طقم بيجاما حرير',
            description: 'Luxurious silk pajama set for ultimate comfort. Includes button-up top and pants.',
            descriptionAr: 'طقم بيجاما حريري فاخر للراحة القصوى. يشمل قميص بأزرار وبنطلون.',
            price: 89.99,
            originalPrice: 119.99,
            images: [
                'https://images.unsplash.com/photo-1616530940355-351fabd9524b?w=800',
            ],
            category: 'lingerie',
            sizes: ['XS', 'S', 'M', 'L', 'XL'],
            colors: [colors.pink, colors.beige, colors.navy],
            inStock: true,
            stock: 20,
            featured: false,
            newArrival: false,
            rating: 4.9,
            reviews: 76,
        },
        {
            id: 'lingerie-3',
            name: 'Seamless Brief Set',
            nameAr: 'طقم سروال بدون درزات',
            description: 'Pack of 3 seamless briefs for invisible wear. Ultra-comfortable microfiber fabric.',
            descriptionAr: 'طقم من 3 سراويل بدون درزات للارتداء الخفي. قماش ميكروفايبر فائق الراحة.',
            price: 34.99,
            images: [
                'https://images.unsplash.com/photo-1582418702059-97ebafb35d09?w=800',
            ],
            category: 'lingerie',
            sizes: ['XS', 'S', 'M', 'L', 'XL'],
            colors: [colors.beige, colors.black, colors.white],
            inStock: true,
            stock: 80,
            featured: false,
            newArrival: true,
            rating: 4.6,
            reviews: 145,
        },
        {
            id: 'jeans-1',
            name: 'Slim Fit Jeans',
            nameAr: 'جينز ضيق',
            description: 'Classic slim fit jeans in premium stretch denim. Comfortable with a modern silhouette.',
            descriptionAr: 'جينز ضيق كلاسيكي من الدنيم المرن الفاخر. مريح بقصة عصرية.',
            price: 79.99,
            originalPrice: 99.99,
            images: [
                'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800',
            ],
            category: 'jeans',
            sizes: ['28', '30', '32', '34', '36', '38'],
            colors: [colors.blue, colors.black, colors.gray],
            inStock: true,
            stock: 55,
            featured: true,
            newArrival: true,
            rating: 4.8,
            reviews: 267,
        },
        {
            id: 'jeans-2',
            name: 'High-Waist Mom Jeans',
            nameAr: 'جينز مام بخصر عالي',
            description: 'Trendy high-waist mom jeans with a relaxed fit. Vintage-inspired wash.',
            descriptionAr: 'جينز مام عصري بخصر عالي وقصة مريحة. غسيل مستوحى من الطراز القديم.',
            price: 69.99,
            images: [
                'https://images.unsplash.com/photo-1584370848010-d7fe6bc767ec?w=800',
            ],
            category: 'jeans',
            sizes: ['24', '26', '28', '30', '32'],
            colors: [colors.blue, colors.black],
            inStock: true,
            stock: 40,
            featured: false,
            newArrival: true,
            rating: 4.7,
            reviews: 189,
        },
        {
            id: 'jeans-3',
            name: 'Relaxed Fit Jeans',
            nameAr: 'جينز بقصة مريحة',
            description: 'Comfortable relaxed fit jeans perfect for casual wear. Features a straight leg design.',
            descriptionAr: 'جينز مريح بقصة واسعة مثالي للارتداء اليومي. يتميز بتصميم ساق مستقيمة.',
            price: 64.99,
            images: [
                'https://images.unsplash.com/photo-1582552938357-32b906df40cb?w=800',
            ],
            category: 'jeans',
            sizes: ['28', '30', '32', '34', '36', '38', '40'],
            colors: [colors.blue, colors.black],
            inStock: true,
            stock: 35,
            featured: false,
            newArrival: false,
            rating: 4.5,
            reviews: 134,
        },
        {
            id: 'jeans-4',
            name: 'Skinny Jeans',
            nameAr: 'جينز سكيني',
            description: 'Form-fitting skinny jeans with stretch for comfort. A wardrobe essential.',
            descriptionAr: 'جينز سكيني محدد للجسم مع مرونة للراحة. قطعة أساسية في خزانة الملابس.',
            price: 59.99,
            originalPrice: 79.99,
            images: [
                'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800',
            ],
            category: 'jeans',
            sizes: ['24', '26', '28', '30', '32', '34'],
            colors: [colors.black, colors.blue, colors.gray],
            inStock: true,
            stock: 22,
            featured: true,
            newArrival: false,
            rating: 4.6,
            reviews: 223,
        },
        {
            id: 'jeans-5',
            name: 'Distressed Denim Jacket',
            nameAr: 'جاكيت جينز ممزق',
            description: 'Classic denim jacket with distressed details for an edgy look. Layer it up.',
            descriptionAr: 'جاكيت جينز كلاسيكي بتفاصيل ممزقة لمظهر جريء. رائع كقطعة إضافية.',
            price: 84.99,
            images: [
                'https://res.cloudinary.com/dfq1xxerr/image/upload/v1/products/jeans-jacket',
            ],
            category: 'jeans',
            sizes: ['S', 'M', 'L', 'XL'],
            colors: [colors.blue, colors.black, colors.gray],
            inStock: true,
            stock: 18,
            newArrival: true,
            rating: 4.7,
            reviews: 42,
        },
        {
            id: 'acc-1',
            name: 'Leather Crossbody Bag',
            nameAr: 'حقيبة جلد كروس',
            description: 'Elegant leather crossbody bag with adjustable strap. Multiple compartments for organization.',
            descriptionAr: 'حقيبة جلد كروس أنيقة بحزام قابل للتعديل. أقسام متعددة للتنظيم.',
            price: 89.99,
            images: [
                'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800',
            ],
            category: 'accessories',
            sizes: ['One Size'],
            colors: [colors.black, colors.brown, colors.beige],
            inStock: true,
            stock: 25,
            featured: true,
            newArrival: true,
            rating: 4.8,
            reviews: 156,
        },
        {
            id: 'acc-2',
            name: 'Classic Watch',
            nameAr: 'ساعة كلاسيكية',
            description: 'Timeless analog watch with leather strap. Elegant design suitable for any occasion.',
            descriptionAr: 'ساعة تناظرية خالدة بحزام جلدي. تصميم أنيق مناسب لأي مناسبة.',
            price: 149.99,
            originalPrice: 199.99,
            images: [
                'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800',
            ],
            category: 'accessories',
            sizes: ['One Size'],
            colors: [colors.black, colors.brown],
            inStock: true,
            stock: 15,
            featured: true,
            newArrival: false,
            rating: 4.9,
            reviews: 89,
        },
        {
            id: 'acc-3',
            name: 'Silk Scarf',
            nameAr: 'وشاح حرير',
            description: 'Luxurious silk scarf with beautiful print. Can be worn multiple ways.',
            descriptionAr: 'وشاح حريري فاخر بطباعة جميلة. يمكن ارتداؤه بطرق متعددة.',
            price: 59.99,
            images: [
                'https://images.unsplash.com/photo-1601924638867-3a6de6b7a500?w=800',
            ],
            category: 'accessories',
            sizes: ['One Size'],
            colors: [colors.red, colors.blue, colors.beige],
            inStock: true,
            stock: 35,
            featured: false,
            newArrival: true,
            rating: 4.7,
            reviews: 67,
        },
        {
            id: 'acc-4',
            name: 'Leather Belt',
            nameAr: 'حزام جلد',
            description: 'Premium leather belt with classic buckle. A timeless accessory for any outfit.',
            descriptionAr: 'حزام جلد فاخر بإبزيم كلاسيكي. إكسسوار خالد لأي إطلالة.',
            price: 49.99,
            images: [
                'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800',
            ],
            category: 'accessories',
            sizes: ['S', 'M', 'L', 'XL'],
            colors: [colors.black, colors.brown],
            inStock: true,
            stock: 50,
            featured: false,
            newArrival: false,
            rating: 4.6,
            reviews: 134,
        },
        {
            id: 'acc-5',
            name: 'Designer Sunglasses',
            nameAr: 'نظارات شمسية مصممة',
            description: 'Stylish designer sunglasses with UV protection. Makes a bold fashion statement.',
            descriptionAr: 'نظارات شمسية أنيقة مع حماية من الأشعة فوق البنفسجية. تصنع بيانًا أزياء جريئًا.',
            price: 129.99,
            originalPrice: 159.99,
            images: [
                'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800',
            ],
            category: 'accessories',
            sizes: ['One Size'],
            colors: [colors.black, colors.brown],
            inStock: true,
            stock: 20,
            featured: true,
            newArrival: true,
            rating: 4.8,
            reviews: 98,
        },
        {
            id: 'acc-6',
            name: 'Sterling Silver Necklace',
            nameAr: 'قلادة فضة إسترليني',
            description: 'Minimalist sterling silver necklace with a delicate pendant. Elegant and understated.',
            descriptionAr: 'قلادة فضية بسيطة مع قلادة رقيقة. أنيقة وبسيطة.',
            price: 99.99,
            images: [
                'https://res.cloudinary.com/dfq1xxerr/image/upload/v1/products/acc-necklace',
            ],
            category: 'accessories',
            sizes: ['One Size'],
            colors: [colors.silver],
            inStock: true,
            stock: 12,
            newArrival: true,
            rating: 4.9,
            reviews: 25,
        },
    ];

    for (const product of productData) {
      const existing = await ctx.db
        .query("products")
        .withIndex("by_manual_id", (q) => q.eq("id", product.id))
        .unique();
      
      if (existing) {
        await ctx.db.patch(existing._id, product);
      } else {
        await ctx.db.insert("products", product);
      }
    }
  },
});
